services:

  321.web:
    repo: /home/s3/321.do
    branch: master
    bin: bin/321.pl
    mode: production
    runner: hypnotoad
    perlbrew: perl-5.42.1
    port: 9321
    logs:
      stdout: /tmp/321.do.stdout.log
      stderr: /tmp/321.do.stderr.log
      ubic: /tmp/321.do.ubic.log
    env:
      MOJO_MODE: production

  123.api:
    repo: /home/s3/api.123.do
    branch: master
    bin: bin/app.pl
    mode: production
    runner: hypnotoad
    port: 9123
    logs:
      stdout: /tmp/123.api.stdout.log
      stderr: /tmp/123.api.stderr.log
      ubic: /tmp/123.api.ubic.log
      app: /tmp/123.api.stdout.log
    env:
      MOJO_MODE: production

  123.web:
    repo: /home/s3/web.123.do
    branch: master
    bin: script/web_123_do
    mode: production
    runner: hypnotoad
    port: 8123
    logs:
      stdout: /tmp/123.web.do.stdout.log
      stderr: /tmp/123.web.do.stderr.log
    env:
      MOJO_MODE: production

  nh.web:
    repo: /home/s3/nigelhamilton.com/mojo
    branch: master
    bin: script/nh
    mode: production
    runner: hypnotoad
    port: 7007
    perlbrew: perl-5.42.1
    logs:
      stdout: /tmp/nh.web.stdout.log
      stderr: /tmp/nh.web.stderr.log
    env:
      MOJO_MODE: production
