package Deploy::Ubic;

use Mojo::Base -base, -signatures;
use Path::Tiny qw(path);

has 'config';  # Deploy::Config instance
has 'log';     # Mojo::Log instance (optional)

sub generate_all ($self) {
    my @results;
    for my $name (@{ $self->config->service_names }) {
        push @results, $self->generate($name);
    }
    return \@results;
}

sub generate ($self, $name) {
    my $svc = $self->config->service($name);
    return { name => $name, status => 'error', message => "Unknown service: $name" } unless $svc;

    my $content = $self->_render_service_file($name, $svc);
    my $file    = $self->_ubic_file_path($name);

    $file->parent->mkpath;
    $file->spew_utf8($content);
    $file->chmod(0600);  # contains env setup, restrict access

    $self->log->info("Generated ubic service file: $file") if $self->log;
    return { name => $name, status => 'ok', path => "$file" };
}

# No more symlinks needed — we write directly to ~/ubic/service/
sub install_symlinks ($self) {
    return [];
}

sub _render_service_file ($self, $name, $svc) {
    my $bin_cmd = $self->_build_bin_cmd($name, $svc);
    my $cwd     = $svc->{repo};
    my $logs    = $svc->{logs} // {};

    my $stdout   = $logs->{stdout}   // "/tmp/$name.stdout.log";
    my $stderr   = $logs->{stderr}   // "/tmp/$name.stderr.log";
    my $ubic_log = $logs->{ubic}     // "/tmp/$name.ubic.log";

    my $mode    = $svc->{mode} // 'production';
    my $runner  = $svc->{runner} // 'hypnotoad';

    # bin_cmd contains shell-quoted env values with embedded single quotes.
    # Escape backslashes and single quotes so the string survives being
    # interpolated into a Perl single-quoted literal in the rendered file.
    my $bin_literal = $bin_cmd =~ s/([\\'])/\\$1/gr;

    return <<"END_UBIC";
use Ubic::Service::SimpleDaemon;

# $name ($mode via $runner) — generated by 321
Ubic::Service::SimpleDaemon->new(
    cwd         =>  '$cwd',
    bin         =>  '$bin_literal',
    stdout      =>  '$stdout',
    stderr      =>  '$stderr',
    ubic_log    =>  '$ubic_log',
);
END_UBIC
}

sub _build_bin_cmd ($self, $name, $svc) {
    my $runner   = $svc->{runner} // 'hypnotoad';
    my $perlbrew = $svc->{perlbrew} // 'perl-5.42.0';
    my $repo     = $svc->{repo};
    my $bin      = "$repo/$svc->{bin}";
    my $port     = $svc->{port};
    my $app_home = $self->config->app_home;

    # Env vars from target config (non-secret, like MOJO_MODE)
    my $env = $svc->{env} // {};
    my %all_env = %$env;
    delete $all_env{$_} for grep { !defined $all_env{$_} || !length $all_env{$_} } keys %all_env;

    # PERL5LIB for repo-local deps
    $all_env{PERL5LIB} = "$repo/local/lib/perl5";

    # Build PATH: repo local/bin + perlbrew perl bin + system
    my $perlbrew_root = $ENV{PERLBREW_ROOT} // "$ENV{HOME}/perl5/perlbrew";
    $all_env{PATH} = join(':',
        "$repo/local/bin",
        "$perlbrew_root/perls/$perlbrew/bin",
        "$perlbrew_root/bin",
        '/usr/local/bin',
        '/usr/bin',
        '/bin',
    );

    my $env_str = '';
    if (%all_env) {
        $env_str = 'env ' . join(' ',
            map { "$_=" . _shell_quote($all_env{$_}) } sort keys %all_env
        ) . ' ';
    }

    # Source secrets from env file at runtime (never baked into the ubic file)
    my $secrets_file = path($app_home, 'secrets', "$name.env");
    my $source_secrets = '';
    if (-f $secrets_file) {
        $source_secrets = "set -a && . $secrets_file && set +a && ";
    }

    if ($runner eq 'morbo') {
        return "bash -c '${source_secrets}perlbrew exec --with $perlbrew ${env_str}morbo -l http://127.0.0.1:$port $bin'";
    }

    # hypnotoad -f — foreground, required by ubic SimpleDaemon
    return "bash -c '${source_secrets}perlbrew exec --with $perlbrew ${env_str}hypnotoad -f $bin'";
}

sub _shell_quote ($val) {
    return "''" unless defined $val && length $val;
    $val =~ s/'/'\\''/g;
    return "'$val'";
}

sub _ubic_file_path ($self, $name) {
    my ($group, $svc_name) = split /\./, $name, 2;
    return path($ENV{HOME}, 'ubic', 'service', $group, $svc_name);
}

1;
