package Deploy::Ubic;

use Mojo::Base -base, -signatures;
use Path::Tiny qw(path);

has 'config';        # Deploy::Config instance
has 'log';           # Mojo::Log instance (optional)
has 'transport';     # Deploy::Local or Deploy::SSH — for remote queries
has 'remote_home';   # override $HOME for remote targets
has 'perlbrew_root'; # override $PERLBREW_ROOT for remote targets

sub generate_all ($self) {
    my @results;
    for my $name (@{ $self->config->service_names }) {
        push @results, $self->generate($name);
    }
    return \@results;
}

sub generate ($self, $name) {
    my $svc = $self->config->service($name);
    return { name => $name, status => 'error', message => "Unknown service: $name" } unless $svc;

    my $content = $self->_render_service_file($name, $svc);

    my $file;
    if ($self->remote_home) {
        # Remote target: write to a temp file locally (caller uploads it)
        require File::Temp;
        my ($group, $svc_name) = split /\./, $name, 2;
        my $tmp = File::Temp->new(SUFFIX => "-$group-$svc_name", UNLINK => 0);
        binmode $tmp, ':utf8';
        print $tmp $content;
        close $tmp;
        chmod 0600, $tmp->filename;
        $file = path($tmp->filename);
    } else {
        # Local target: write directly to ~/ubic/service/
        $file = $self->_ubic_file_path($name);
        $file->parent->mkpath;
        $file->spew_utf8($content);
        $file->chmod(0600);
    }

    $self->log->info("Generated ubic service file: $file") if $self->log;
    return { name => $name, status => 'ok', path => "$file" };
}

sub stale ($self, $name) {
    return 0 if $self->remote_home;  # remote: caller drives via deploy flow
    my $svc = $self->config->service($name) or return 0;
    my $repo = $svc->{repo} or return 0;
    my $manifest = path($repo, '321.yml');
    return 0 unless $manifest->exists;

    my $ubic_file = $self->_ubic_file_path($name);
    return 1 unless $ubic_file->exists;
    return $manifest->stat->mtime > $ubic_file->stat->mtime;
}

sub regenerate_if_stale ($self, $name) {
    return undef unless $self->stale($name);
    return $self->generate($name);
}

sub upload_remote ($self, $transport, $name, $gen) {
    my ($group, $svc_name) = split /\./, $name, 2;
    my $dest = "~/ubic/service/$group/$svc_name";
    $transport->run("mkdir -p ~/ubic/service/$group");
    # Drop any stale symlink/file first; old layouts pointed at
    # <repo>/ubic/... and scp would either write through the dangling link
    # silently (broken target) or update the wrong file (live target).
    $transport->run("rm -f $dest");
    $transport->upload($gen->{path}, $dest);
}

# Detect remote HOME and PERLBREW_ROOT via transport (single SSH call)
sub detect_remote ($self) {
    return unless $self->transport;
    my $r = $self->transport->run('echo HOME=$HOME PERLBREW_ROOT=$PERLBREW_ROOT');
    if ($r->{ok} && $r->{output} =~ /HOME=(\S+)/) {
        $self->remote_home($1);
    }
    if ($r->{ok} && $r->{output} =~ /PERLBREW_ROOT=(\S+)/) {
        $self->perlbrew_root($1);
    } else {
        $self->perlbrew_root($self->_home . '/perl5/perlbrew');
    }
    return $self;
}

sub _home ($self) {
    return $self->remote_home // $ENV{HOME};
}

sub _perlbrew_root ($self) {
    return $self->perlbrew_root // $ENV{PERLBREW_ROOT} // ($self->_home . '/perl5/perlbrew');
}

sub _render_service_file ($self, $name, $svc) {
    my $bin_cmd = $self->_build_bin_cmd($name, $svc);
    my $cwd     = $svc->{repo};
    my $logs    = $svc->{logs} // {};

    my $stdout   = $logs->{stdout}   // "/tmp/$name.stdout.log";
    my $stderr   = $logs->{stderr}   // "/tmp/$name.stderr.log";
    my $ubic_log = $logs->{ubic}     // "/tmp/$name.ubic.log";

    my $mode    = $svc->{mode} // 'production';
    my $runner  = $svc->{runner} // 'hypnotoad';

    my $bin_literal = $bin_cmd =~ s/([\\'])/\\$1/gr;

    return <<"END_UBIC";
use Ubic::Service::SimpleDaemon;

# $name ($mode via $runner) — generated by 321
Ubic::Service::SimpleDaemon->new(
    cwd         =>  '$cwd',
    bin         =>  '$bin_literal',
    stdout      =>  '$stdout',
    stderr      =>  '$stderr',
    ubic_log    =>  '$ubic_log',
);
END_UBIC
}

sub _build_bin_cmd ($self, $name, $svc) {
    my $runner   = $svc->{runner} // 'hypnotoad';
    my $perlbrew = $svc->{perlbrew} // 'perl-5.42.0';
    my $repo     = $svc->{repo};
    my $bin      = "$repo/$svc->{bin}";
    my $port     = $svc->{port};

    my $home          = $self->_home;
    my $perlbrew_root = $self->_perlbrew_root;
    my $app_home      = $self->config->app_home;

    # Env vars from target config
    my $env = $svc->{env} // {};
    my %all_env = %$env;
    delete $all_env{$_} for grep { !defined $all_env{$_} || !length $all_env{$_} } keys %all_env;

    # Set MOJO_MODE from the resolved mode (dev = development, live = production)
    $all_env{MOJO_MODE} //= $svc->{mode} // 'production';

    # PERL5LIB for repo-local deps
    $all_env{PERL5LIB} = "$repo/local/lib/perl5";

    # Build PATH: repo local/bin + perlbrew perl bin + system
    $all_env{PATH} = join(':',
        "$repo/local/bin",
        "$perlbrew_root/perls/$perlbrew/bin",
        "$perlbrew_root/bin",
        '/usr/local/bin',
        '/usr/bin',
        '/bin',
    );

    my $env_str = '';
    if (%all_env) {
        $env_str = 'env ' . join(' ',
            map { "$_=" . _shell_quote($all_env{$_}) } sort keys %all_env
        ) . ' ';
    }

    # Source secrets from env file at runtime (never baked into the ubic file)
    my $secrets_path = "$app_home/secrets/$name.env";
    my $source_secrets = "test -f $secrets_path && { set -a && . $secrets_path && set +a; }; ";

    # hypnotoad -f keeps the process foreground; ubic SimpleDaemon requires that
    my %tail = (
        script    => "perl $bin",
        morbo     => "morbo -l http://127.0.0.1:$port $bin",
        hypnotoad => "hypnotoad -f $bin",
    );
    my $cmd = $tail{$runner} // $tail{hypnotoad};
    return "bash -c '${source_secrets}perlbrew exec --with $perlbrew ${env_str}$cmd'";
}

# Parse `ubic status` output into { name => { pid, raw } }.
# Centralised so callers don't reinvent the regex.
sub parse_status_output ($class, $text) {
    my %statuses;
    for my $line (split /\n/, $text // '') {
        next unless $line =~ /^\s+(\S+)\t+(.+)/;
        my ($name, $raw) = ($1, $2);
        my $pid = $raw =~ /running \(pid (\d+)\)/ ? $1 : undef;
        $statuses{$name} = { pid => $pid, raw => $raw };
    }
    return \%statuses;
}

sub _shell_quote ($val) {
    return "''" unless defined $val && length $val;
    $val =~ s/'/'\\''/g;
    return "'$val'";
}

sub _ubic_file_path ($self, $name) {
    my ($group, $svc_name) = split /\./, $name, 2;
    return path($self->_home, 'ubic', 'service', $group, $svc_name);
}

1;
